development:
  adapter: postgresql
  encoding: unicode
  database: ride_hailing
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: database-test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: ENV['DATABASE_URL']
  pool: 5
  timeout: 5000